import Mathlib.RingTheory.PicardGroup
import Mathlib.RingTheory.ClassGroup

open scoped TensorProduct
open scoped nonZeroDivisors

/-!
## Picard group vs. ideal class group

This project’s first goal is to formalize (at least the statement of) the classical result that,
for a commutative domain, the Picard group is (canonically) isomorphic to the ideal class group.
-/

namespace Picard

section TorsionFree

variable {R : Type*} [CommRing R] [IsDomain R]
variable {P : Type*} [AddCommGroup P] [Module R P] [Module.Projective R P]
variable (K : Type*) [Field K] [Algebra R K] [IsFractionRing R K]
variable (M : Type*) [AddCommGroup M] [Module R M]
variable (I : Type*) [AddCommGroup I] [Module R I]

section Setup


/-! ### Theorem 11.6 -/

/-- (11.6.a) An `R`-module is invertible iff the canonical map `Mᵛ ⊗[R] M →ₗ[R] R` is an isomorphism. -/
theorem theorem_11_6_a :
    Module.Invertible R M ↔ Nonempty ((Module.Dual R M ⊗[R] M) ≃ₗ[R] R) := by
  sorry

/-- (11.6.b, first part) An invertible module is isomorphic to a fractional ideal of `R`. -/
theorem theorem_11_6_b₁ :
    Module.Invertible R M → ∃ I : Submodule R K, Nonempty (M ≃ₗ[R] I) := by
  sorry

/-- (11.6.b, second part) An invertible fractional ideal contains a nonzerodivisor of `R`. -/
theorem theorem_11_6_b₂ (I : Submodule R K) (hI : IsUnit I) :
    ∃ a : R, IsRegular a ∧ algebraMap R K a ∈ I := by
  sorry

/-- (11.6.c, first part) For invertible submodules `I, J ⊆ K(R)`, the natural map
`I ⊗[R] J → I * J` is an isomorphism. -/
theorem theorem_11_6_c₁ (I J : Submodule R K) (hI : IsUnit I) (hJ : IsUnit J) :
    Nonempty ((I ⊗[R] J) ≃ₗ[R] (I * J)) := by
  sorry

/-- (11.6.c, second part) For invertible submodules `I, J ⊆ K(R)`, the natural map
`I⁻¹ * J → Hom_R(I, J)` is an isomorphism. -/
theorem theorem_11_6_c₂ (I J : Submodule R K) (hI : IsUnit I) (hJ : IsUnit J) :
    Nonempty ((I⁻¹ * J) ≃ₗ[R] (I →ₗ[R] J)) := by
  sorry

/-- (11.6.c, consequence) The inverse submodule is linearly isomorphic to the dual. -/
theorem theorem_11_6_c₃ (I : Submodule R K) (hI : IsUnit I) :
    Nonempty (I⁻¹ ≃ₗ[R] Module.Dual R I) := by
  sorry

/-- (11.6.d) An `R`-submodule `I ⊆ K(R)` is invertible iff `I⁻¹ * I = 1`. -/
theorem theorem_11_6_d (I : Submodule R K) :
    IsUnit I ↔ I⁻¹ * I = (1 : Submodule R K) := by
  sorry

/-! ### Corollary 11.7 -/

abbrev CartierGroup : Type v := Units (Submodule R K)

/-- The generators coming from invertible ideals of `R` viewed inside `K(R)`. -/
def invertibleIdealGenerators : Set (CartierGroup (R:=R) (K:=K)) :=
  {u | ∃ I : Ideal R, u.val = Submodule.map (Algebra.linearMap R K) I.toSubmodule}

/-- (11.7.a) The map from invertible submodules of `K(R)` to the Picard group is surjective. -/
theorem corollary_11_7_a_surjective :
    Function.Surjective (Submodule.unitsToPic (R:=R) (A:=K)) := by
  classical
  -- `range_unitsToPic` identifies the range with the relative Picard group.
  have hRange : (Submodule.unitsToPic (R:=R) (A:=K)).range = Submodule.relPic (R:=R) (A:=K) :=
    Submodule.range_unitsToPic (R:=R) (A:=K)
  -- Over a field `K`, the Picard group is trivial, so the relative Picard is top.
  have hTop : Submodule.relPic (R:=R) (A:=K) = ⊤ := Submodule.relPic_eq_top (R:=R) (A:=K)
  have hRangeTop : (Submodule.unitsToPic (R:=R) (A:=K)).range = ⊤ := by
    simpa [hRange, hTop]
  intro M
  have : M ∈ (Submodule.unitsToPic (R:=R) (A:=K)).range := by
    simpa [hRangeTop] using (show M ∈ (⊤ : Subgroup _) from trivial)
  rcases this with ⟨u, rfl⟩
  exact ⟨u, rfl⟩

/-- (11.7.a) The kernel of the map to the Picard group is the group of units of `K(R)`. -/
theorem corollary_11_7_a_kernel :
    (Submodule.unitsToPic (R:=R) (A:=K)).ker ≃* Units K := by
  classical
  -- First, identify the kernel with the range of principal divisors.
  have hKer : (Submodule.unitsToPic (R:=R) (A:=K)).ker =
      (Units.map (spanSingleton R).toMonoidHom).range :=
      Submodule.ker_unitsToPic (R:=R) (A:=K)
  -- The range of `Units.map` is canonically isomorphic to `Units K`.
  let principalRange : Units K ≃* (Units.map (spanSingleton R).toMonoidHom).range :=
    { toFun := fun u => ⟨Units.map (spanSingleton R).toMonoidHom u, ⟨u, rfl⟩⟩
      , invFun := fun u => Classical.choose u.property
      , left_inv := by
        intro u; rfl
      , right_inv := by
        intro u
        rcases u with ⟨u, ⟨v, rfl⟩⟩
        simp
      , map_mul' := by intro u v; rfl }
  -- Transport along the identification of the kernel with that range.
  have hRangeKer : (Units.map (spanSingleton R).toMonoidHom).range ≃*
      (Submodule.unitsToPic (R:=R) (A:=K)).ker :=
      MulEquiv.subgroupCongr hKer.symm
  exact principalRange.trans hRangeKer

/-- (11.7.b) The Cartier group is generated by the invertible ideals of `R`. -/
theorem corollary_11_7_b :
    Subgroup.closure (invertibleIdealGenerators (R:=R) (K:=K)) = ⊤ := by
  sorry

end Setup

end Eisenbud
