import Mathlib.RingTheory.ClassGroup
import Mathlib.RingTheory.FractionalIdeal.Operations
import Mathlib.RingTheory.UniqueFactorizationDomain.Basic

open scoped nonZeroDivisors

namespace Picard

open IsLocalization IsFractionRing FractionalIdeal

section Domain

variable (R : Type*) [CommRing R] [IsDomain R]

/-!
## Triviality of the ideal class group of a UFD

The key input is the commutative algebra statement:

> If `R` is a UFD and `I ⊆ R` is an ideal such that its image in the monoid of fractional ideals
> is invertible, then `I` is principal.

The user-provided proof sketch is implemented as a lemma with several subordinate lemmas; the
hard commutative algebra steps are currently left as `sorry`.
-/

lemma ideal_ne_bot_of_isUnit_fractionalIdeal {I : Ideal R}
    (hI : IsUnit (I : FractionalIdeal R⁰ (FractionRing R))) : I ≠ ⊥ := by
  intro hbot
  have : IsUnit (0 : FractionalIdeal R⁰ (FractionRing R)) := by simp [hbot] at hI
  exact (not_isUnit_zero : ¬IsUnit (0 : FractionalIdeal R⁰ (FractionRing R))) this

lemma exists_ne_zero_mem_of_isUnit_fractionalIdeal {I : Ideal R}
    (hI : IsUnit (I : FractionalIdeal R⁰ (FractionRing R))) :
    ∃ f : R, f ∈ I ∧ f ≠ 0 := by
  classical
  have hne : I ≠ ⊥ := ideal_ne_bot_of_isUnit_fractionalIdeal (R := R) hI
  rcases Submodule.exists_mem_ne_zero_of_ne_bot hne with ⟨f, hfI, hf0⟩
  exact ⟨f, hfI, hf0⟩

/-!
### The main commutative algebra input (proof sketch)

This lemma is the heart of the proof sketch. It should be filled in by implementing the
localization/factorization argument described in the prompt.
-/

/-- In a UFD, an integral ideal that is invertible as a fractional ideal is principal. -/
lemma fractionalIdeal_isPrincipal_of_num_isPrincipal
    (I : FractionalIdeal R⁰ (FractionRing R)) (hI : I.num.IsPrincipal) :
    (I : Submodule R (FractionRing R)).IsPrincipal := by
  classical
  -- Put the principal structure on `I.num` so we can use its generator.
  letI : I.num.IsPrincipal := hI
  let g : R := Submodule.IsPrincipal.generator I.num
  have hnum : (I.num : FractionalIdeal R⁰ (FractionRing R)) =
      FractionalIdeal.spanSingleton (R⁰) (algebraMap R (FractionRing R) g) := by
    -- `I.num = (g)` as an ideal, hence as a fractional ideal.
    have hg : (I.num : Ideal R) = Ideal.span ({g} : Set R) := by
      simp [g] --using (Ideal.span_singleton_generator (I := I.num)).symm
    calc
      (I.num : FractionalIdeal R⁰ (FractionRing R)) =
          ((Ideal.span ({g} : Set R) : Ideal R) : FractionalIdeal R⁰ (FractionRing R)) := by
            simp [hg]
      _ = FractionalIdeal.spanSingleton (R⁰) (algebraMap R (FractionRing R) g) := by
            simp-- using
              --(FractionalIdeal.coeIdeal_span_singleton (S := (R⁰)) (P := FractionRing R) g)
  -- Clear denominators using `den_mul_self_eq_num'`, and cancel the principal fractional ideal
  -- generated by the denominator.
  have hdenmul :
      FractionalIdeal.spanSingleton (R⁰) (algebraMap R (FractionRing R) (I.den : R)) * I =
        FractionalIdeal.spanSingleton (R⁰) (algebraMap R (FractionRing R) g) := by
    simpa [hnum] using (FractionalIdeal.den_mul_self_eq_num' (S := (R⁰)) (P := FractionRing R) I)
  -- Multiply by the inverse of the (nonzero) principal fractional ideal generated by `I.den`.
  have hcancel :=
    congrArg
      (fun J =>
        (1 / FractionalIdeal.spanSingleton (R⁰)
              (algebraMap R (FractionRing R) (I.den : R))) * J)
      hdenmul
  -- Simplify: `1 / spanSingleton x = spanSingleton x⁻¹`, and `spanSingleton` multiplies.
  have : I =
      FractionalIdeal.spanSingleton (R⁰)
        ((algebraMap R (FractionRing R) g) *
          (algebraMap R (FractionRing R) (I.den : R))⁻¹) := by
    simpa [mul_assoc, FractionalIdeal.one_div_spanSingleton,
      FractionalIdeal.spanSingleton_mul_spanSingleton, mul_comm, mul_left_comm] using hcancel
  -- Conclude `I` is principal as an `R`-submodule of `FractionRing R`.
  refine (FractionalIdeal.isPrincipal_iff (S := (R⁰)) (P := FractionRing R) I).2 ?_
  exact ⟨_, this⟩

end Domain

section UFD

variable (R : Type*) [CommRing R] [IsDomain R] [UniqueFactorizationMonoid R]

/-!
### The main commutative algebra input (proof sketch)

This lemma is the heart of the proof sketch. It should be filled in by implementing the
localization/factorization argument described in the prompt.
-/

/-- In a UFD, an integral ideal that is invertible as a fractional ideal is principal. -/
theorem ideal_isPrincipal_of_isUnit_fractionalIdeal (I : Ideal R)
    (hI : IsUnit (I : FractionalIdeal R⁰ (FractionRing R))) :
    I.IsPrincipal := by
  classical
  -- Step 1: pick a nonzero `f ∈ I`.
  obtain ⟨f, hfI, hf0⟩ := exists_ne_zero_mem_of_isUnit_fractionalIdeal (R := R) (I := I) hI

  -- Step 2: factor `f` into prime elements, choose local principalizations around each prime,
  -- and define the candidate generator `h` as a product of primes to certain exponents.
  --
  -- Step 3: show `I = (h)`, by checking after localizing at elements on a principal cover,
  -- and comparing prime exponents using uniqueness of factorization.
  --
  -- The commutative algebra content is nontrivial; we leave it as `sorry` for now.
  -- The values `f`, `hfI`, `hf0` are recorded so the statement matches the proof sketch.
  sorry

/-!
### UFD implies class group is trivial
-/

/-- In a UFD, every invertible fractional ideal is principal. -/
theorem fractionalIdeal_isPrincipal_of_ufd (I : (FractionalIdeal R⁰ (FractionRing R))ˣ) :
    (I : Submodule R (FractionRing R)).IsPrincipal := by
  classical
  let J : Ideal R := (I : FractionalIdeal R⁰ (FractionRing R)).num
  have hJunit : IsUnit (J : FractionalIdeal R⁰ (FractionRing R)) := by
    have hIunit : IsUnit (I : FractionalIdeal R⁰ (FractionRing R)) := ⟨I, rfl⟩
    -- `J = spanSingleton den * I`, and both factors are units.
    have hden0 :
        algebraMap R (FractionRing R)
            (((I : FractionalIdeal R⁰ (FractionRing R)).den : R⁰) : R) ≠ 0 := by
      exact IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors
        (SetLike.coe_mem ((I : FractionalIdeal R⁰ (FractionRing R)).den))
    let u : (FractionRing R)ˣ :=
      Units.mk0
        (algebraMap R (FractionRing R)
          (((I : FractionalIdeal R⁰ (FractionRing R)).den : R⁰) : R))
        hden0
    have hdenUnit :
        IsUnit
          (FractionalIdeal.spanSingleton (R⁰)
            (algebraMap R (FractionRing R)
              (((I : FractionalIdeal R⁰ (FractionRing R)).den : R⁰) : R))) := by
      refine ⟨toPrincipalIdeal R (FractionRing R) u, ?_⟩
      simp [u] --using (coe_toPrincipalIdeal (R := R) (K := FractionRing R) u)
    have hmul :
        FractionalIdeal.spanSingleton (R⁰)
            (algebraMap R (FractionRing R)
              (((I : FractionalIdeal R⁰ (FractionRing R)).den : R⁰) : R)) *
          (I : FractionalIdeal R⁰ (FractionRing R)) = J := by
      simpa [J] using
        (FractionalIdeal.den_mul_self_eq_num' (S := (R⁰)) (P := FractionRing R)
          (I := (I : FractionalIdeal R⁰ (FractionRing R))))
    -- Transport `IsUnit` along the equality.
    simpa [hmul] using hdenUnit.mul hIunit
  have hJprin : J.IsPrincipal :=
    ideal_isPrincipal_of_isUnit_fractionalIdeal (R := R) J hJunit
  -- If the numerator ideal is principal, the fractional ideal is principal.
  simpa [J] using
    fractionalIdeal_isPrincipal_of_num_isPrincipal (R := R)
      (I := (I : FractionalIdeal R⁰ (FractionRing R))) hJprin

/-- In a UFD, every class in the ideal class group is `1`. -/
theorem classGroup_eq_one_of_ufd (x : ClassGroup R) : x = 1 := by
  classical
  refine ClassGroup.induction (R := R) (K := FractionRing R) (P := fun y => y = 1) ?_ x
  intro I
  -- `mk I = 1` iff `I` is principal as a submodule.
  refine (ClassGroup.mk_eq_one_iff (R := R) (K := FractionRing R) (I := I)).2 ?_
  exact fractionalIdeal_isPrincipal_of_ufd (R := R) I

/-- The ideal class group of a UFD is trivial (as a subsingleton type). -/
theorem subsingleton_classGroup_of_ufd : Subsingleton (ClassGroup R) := by
  classical
  refine ⟨fun x y => ?_⟩
  calc
    x = 1 := classGroup_eq_one_of_ufd (R := R) x
    _ = y := (classGroup_eq_one_of_ufd (R := R) y).symm

end UFD

end Picard
